<?php
$code = $this->code;
$retour = array();
switch ($code) {
    case 201:
        $this->status = "success";
        $this->message = "reveil cree";
        $retour = array( 
            "status" => $this->status,
            "code" => $this->code,
            "message" => $this->message,
            "reveil" => $this->reveil->getState()
            );
        break;
    case 400:
        $this->status = "error";
        $this->message = "parametre incorrect";
        $retour = array( 
            "status" => $this->status,
            "code" => $this->code,
            "message" => $this->message
            );
        break;
    default:
        $this->code = 520;
        $this->status = "error";
        $this->message = "une erreur est survenue";
        $retour = array( 
            "status" => $this->status,
            "code" => $this->code,
            "message" => $this->message
            );
        break;
}

echo json_encode( $retour );