<?php
$code = $this->code;
switch ($code) {
    case 200:
        $this->status = "success";
        $this->message = "lumiere eteinte";
        break;
    case 404:
        $this->status = "error";
        $this->message = "piece non trouvee";
        break;
    case 444:
        $this->status = "error";
        $this->message = "pas de lumiere dans cette piece";
        break;
    default:
        $this->code = "520";
        $this->status = "error";
        $this->message = "une erreur est survenue";
        break;
}

echo json_encode( array( 
    "status" => $this->status,
    "code" => $this->code,
    "message" => $this->message
    ) );