<?php
if( $this->isUpdated ) {
    $code = $this->code;
    $retour = array();
    switch ($code) {
        case 202:
            $this->status = "success";
            $this->message = "status";
            $retour = array( 
                "status" => $this->status,
                "code" => $this->code,
                "message" => $this->message,
                "state" => $this->state
                );
            break;
        case 400:
            $this->status = "error";
            $this->message = "parametre incorrect";
            $retour = array( 
                "status" => $this->status,
                "code" => $this->code,
                "message" => $this->message
                );
            break;
        default:
            $this->code = 520;
            $this->status = "error";
            $this->message = "une erreur est survenue";
            $retour = array( 
                "status" => $this->status,
                "code" => $this->code,
                "message" => $this->message
                );
            break;
    }
}
else {
 /**
 * LONG POLLING
 */
    $retour = array( 
        "status" => 'no content',
        "code" => 204,
        "message" => 'no content'
        );
}

$retour['timestamp'] = time();
echo json_encode( $retour );